import { report, settle, exitCode } from './helpers.js'

await import('./money.test.js')
await import('./migrate.test.js')
await import('./schema.test.js')
await import('./health.test.js')
await import('./auth.test.js')
await import('./updates.test.js')
await import('./menu.test.js')
await import('./tables.test.js')
await import('./business-date.test.js')
await import('./bill-math.test.js')
await import('./bill-number.test.js')
await import('./orders.test.js')
await import('./bills.test.js')
await import('./reports.test.js')
await import('./sync.test.js')
await import('./print.test.js')
await import('./print-queue.test.js')
await import('./settings.test.js')
await import('./logo.test.js')
await import('./preview.test.js')

await settle()
report('backend')
process.exit(exitCode())
