-- Counterpart to sqlite/0004. The cloud does not track its own sync state --
-- these columns exist only so the row shape matches on push.

ALTER TABLE branches ADD COLUMN IF NOT EXISTS sync_attempts INTEGER NOT NULL DEFAULT 0;
ALTER TABLE branches ADD COLUMN IF NOT EXISTS sync_error TEXT;
ALTER TABLE users ADD COLUMN IF NOT EXISTS sync_attempts INTEGER NOT NULL DEFAULT 0;
ALTER TABLE users ADD COLUMN IF NOT EXISTS sync_error TEXT;
ALTER TABLE sections ADD COLUMN IF NOT EXISTS sync_attempts INTEGER NOT NULL DEFAULT 0;
ALTER TABLE sections ADD COLUMN IF NOT EXISTS sync_error TEXT;
ALTER TABLE tables ADD COLUMN IF NOT EXISTS sync_attempts INTEGER NOT NULL DEFAULT 0;
ALTER TABLE tables ADD COLUMN IF NOT EXISTS sync_error TEXT;
ALTER TABLE categories ADD COLUMN IF NOT EXISTS sync_attempts INTEGER NOT NULL DEFAULT 0;
ALTER TABLE categories ADD COLUMN IF NOT EXISTS sync_error TEXT;
ALTER TABLE menu_items ADD COLUMN IF NOT EXISTS sync_attempts INTEGER NOT NULL DEFAULT 0;
ALTER TABLE menu_items ADD COLUMN IF NOT EXISTS sync_error TEXT;
ALTER TABLE menu_item_variants ADD COLUMN IF NOT EXISTS sync_attempts INTEGER NOT NULL DEFAULT 0;
ALTER TABLE menu_item_variants ADD COLUMN IF NOT EXISTS sync_error TEXT;
ALTER TABLE reservations ADD COLUMN IF NOT EXISTS sync_attempts INTEGER NOT NULL DEFAULT 0;
ALTER TABLE reservations ADD COLUMN IF NOT EXISTS sync_error TEXT;
ALTER TABLE orders ADD COLUMN IF NOT EXISTS sync_attempts INTEGER NOT NULL DEFAULT 0;
ALTER TABLE orders ADD COLUMN IF NOT EXISTS sync_error TEXT;
ALTER TABLE order_items ADD COLUMN IF NOT EXISTS sync_attempts INTEGER NOT NULL DEFAULT 0;
ALTER TABLE order_items ADD COLUMN IF NOT EXISTS sync_error TEXT;
ALTER TABLE bills ADD COLUMN IF NOT EXISTS sync_attempts INTEGER NOT NULL DEFAULT 0;
ALTER TABLE bills ADD COLUMN IF NOT EXISTS sync_error TEXT;
ALTER TABLE payments ADD COLUMN IF NOT EXISTS sync_attempts INTEGER NOT NULL DEFAULT 0;
ALTER TABLE payments ADD COLUMN IF NOT EXISTS sync_error TEXT;
